"""add unique constraint to question title

Revision ID: 8992946e43e6
Revises: 6f5141058dbb
Create Date: 2026-06-13 17:11:03.961294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8992946e43e6'
down_revision: Union[str, Sequence[str], None] = '6f5141058dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_states_due'), ['due'], unique=False)

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_records_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('interview_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_is_active'), ['is_active'], unique=False)
        batch_op.create_unique_constraint('uq_questions_title', ['title'])

    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_logs_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_logs_question_id'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_questions_is_active'))
        batch_op.drop_index(batch_op.f('ix_questions_category_id'))

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_question_id'))

    with op.batch_alter_table('interview_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_messages_session_id'))

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_records_question_id'))

    with op.batch_alter_table('card_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_states_due'))

    # ### end Alembic commands ###
